- hosts: localhost
  connection: local

  tasks:
    - name: Try to ssh into our raspberry pi emualator
      wait_for:
        port: 2222
        delay: 1
        timeout: 300
        state: started

    - name: SSH Avaliable
      debug:
        msg: SSH is now available attempting to login
